[profile.default]
src = "contracts"
test = "test"
out = "out"
libs = ["lib"]
fs_permissions = [{ access = "read", path = "./" }]
ignored = ["lib/openzeppelin-contracts/certora"]
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "forge-std/=lib/forge-std/src/"
]
